export const IDBoxStyles = {
  width: "480px",
  height: "50px",
  margin: "18px",
  padding: "0px 20px",
  placeholder: "아이디",
  placeholderColor: "#D0D2E0",
  placeholderWeight: "800",
  placeholderSize: "20px",
  borderWidth: "1px",
  borderStyle: "solid",
  borderColor: "#D0D2E0",
  borderRadius: "5px",
};

export const PWBoxStyles = {
  width: "480px",
  height: "50px",
  margin: "18px",
  padding: "0px 20px",
  placeholder: "비밀번호",
  placeholderColor: "#D0D2E0",
  placeholderWeight: "800",
  placeholderSize: "20px",
  borderWidth: "1px",
  borderStyle: "solid",
  borderColor: "#D0D2E0",
  borderRadius: "5px",
};

export const SubmitStyles = {
  width: "162px",
  height: "45px",
  margin: "10px",
  padding: "2px",
  borderWidth: "1px",
  borderStyle: "solid",
  borderColor: "#D0D2E0",
  borderRadius: "10px",
  shadow: "0px 4px 4px",
  shadowColor: "#D0D2E0",
  fontSize: "25px",
  fontWeight: "800",
  color: "#000000",
  backgroundColor: "#ffffff",
  transitionTime: "0.2s",
};
